version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8500:8500"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - UTAGE_WEBHOOK_SECRET=${UTAGE_WEBHOOK_SECRET}
      - EMAIL_API_KEY=${EMAIL_API_KEY}
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    networks:
      - kantei-network

  frontend:
    build: ./frontend
    ports:
      - "3500:3500"
    environment:
      - VITE_API_URL=http://localhost:8500
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - kantei-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - kantei-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kantei-network

volumes:
  postgres_data:
  redis_data:

networks:
  kantei-network:
    driver: bridge