"""Initial migration: Create all tables

Revision ID: b23cbb44689a
Revises: 
Create Date: 2025-09-18 12:08:04.428605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23cbb44689a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False, comment='設定キー'),
    sa.Column('setting_value', sa.Text(), nullable=True, comment='設定値（JSON可）'),
    sa.Column('description', sa.Text(), nullable=True, comment='設定の説明'),
    sa.Column('setting_type', sa.String(length=50), nullable=False, comment='値の型: string/json/boolean/number'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='公開設定（フロントエンドアクセス可否）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_key', 'system_settings', ['setting_key'], unique=False)
    op.create_index('idx_system_public', 'system_settings', ['is_public'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='ログイン用メールアドレス'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcryptハッシュ化パスワード（内部のみ）'),
    sa.Column('business_name', sa.String(length=255), nullable=True, comment='屋号・事業者名'),
    sa.Column('operator_name', sa.String(length=255), nullable=True, comment='運営者名'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='アカウント有効状態'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='管理者権限'),
    sa.Column('utage_user_id', sa.String(length=255), nullable=True, comment='UTAGE連携ID'),
    sa.Column('subscription_status', sa.String(length=50), nullable=False, comment='課金状態: active/inactive/suspended'),
    sa.Column('subscription_updated_at', sa.DateTime(), nullable=True, comment='課金状態最終更新時刻'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='論理削除日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_utage_subscription', 'users', ['utage_user_id', 'subscription_status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_utage_user_id'), 'users', ['utage_user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作種別'),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment='対象エンティティ種別'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='対象エンティティID'),
    sa.Column('details', sa.JSON(), nullable=True, comment='操作詳細情報'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作元IPアドレス'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='ユーザーエージェント'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('kantei_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False, comment='クライアント氏名'),
    sa.Column('client_email', sa.String(length=255), nullable=True, comment='クライアントメールアドレス'),
    sa.Column('client_info', sa.JSON(), nullable=False, comment='\n    クライアント詳細情報: {\n        "name": "氏名",\n        "birth_date": "生年月日",\n        "birth_time": "出生時刻（任意）",\n        "gender": "性別",\n        "birth_place": "出生地（任意）"\n    }\n    '),
    sa.Column('calculation_result', sa.JSON(), nullable=False, comment='\n    鑑定計算結果: {\n        "kyusei_kigaku": {...},    # 九星気学結果\n        "seimei_handan": {...},    # 姓名判断結果\n        "kichihoui": {...},        # 吉方位結果\n        "template_ids": [...]      # 使用テンプレートID一覧\n    }\n    '),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='生成PDFのURL/パス'),
    sa.Column('pdf_file_size', sa.Integer(), nullable=True, comment='PDFファイルサイズ（バイト）'),
    sa.Column('pdf_generated_at', sa.DateTime(), nullable=True, comment='PDF生成日時'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状態: created/processing/completed/failed'),
    sa.Column('custom_message', sa.Text(), nullable=True, comment='カスタムメッセージ'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='論理削除日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kantei_client_name', 'kantei_records', ['client_name'], unique=False)
    op.create_index('idx_kantei_created_at', 'kantei_records', ['created_at'], unique=False)
    op.create_index('idx_kantei_status', 'kantei_records', ['status'], unique=False)
    op.create_index('idx_kantei_user_created', 'kantei_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_kantei_records_client_name'), 'kantei_records', ['client_name'], unique=False)
    op.create_index(op.f('ix_kantei_records_id'), 'kantei_records', ['id'], unique=False)
    op.create_index(op.f('ix_kantei_records_user_id'), 'kantei_records', ['user_id'], unique=False)
    op.create_table('template_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='ロゴ画像URL/パス'),
    sa.Column('logo_file_size', sa.Integer(), nullable=True, comment='ロゴファイルサイズ（バイト）'),
    sa.Column('business_name', sa.String(length=255), nullable=False, comment='屋号・事業者名'),
    sa.Column('operator_name', sa.String(length=255), nullable=False, comment='運営者名'),
    sa.Column('color_theme', sa.String(length=50), nullable=False, comment='カラーテーマ: default/blue/green/purple等'),
    sa.Column('font_family', sa.String(length=100), nullable=False, comment='フォントファミリー'),
    sa.Column('layout_style', sa.String(length=50), nullable=False, comment='レイアウトスタイル'),
    sa.Column('custom_css', sa.Text(), nullable=True, comment='カスタムCSS（任意）'),
    sa.Column('settings_version', sa.String(length=20), nullable=False, comment='設定バージョン'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_updated', 'template_settings', ['updated_at'], unique=False)
    op.create_index('idx_template_user', 'template_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_template_settings_id'), 'template_settings', ['id'], unique=False)
    op.create_index(op.f('ix_template_settings_user_id'), 'template_settings', ['user_id'], unique=True)
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kantei_record_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False, comment='送信先メールアドレス'),
    sa.Column('sender_name', sa.String(length=255), nullable=True, comment='送信者名（カスタマイズ用）'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='メール件名'),
    sa.Column('message_content', sa.Text(), nullable=True, comment='メール本文'),
    sa.Column('message_id', sa.String(length=255), nullable=True, comment='送信サービスのメッセージID'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='送信プロバイダー: sendgrid/mailgun等'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状態: pending/sent/failed/bounced'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='エラー詳細（失敗時）'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='送信実行時刻'),
    sa.Column('delivered_at', sa.DateTime(), nullable=True, comment='配信確認時刻'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kantei_record_id'], ['kantei_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_kantei_sent', 'email_history', ['kantei_record_id', 'sent_at'], unique=False)
    op.create_index('idx_email_message_id', 'email_history', ['message_id'], unique=False)
    op.create_index('idx_email_recipient', 'email_history', ['recipient_email'], unique=False)
    op.create_index('idx_email_status', 'email_history', ['status'], unique=False)
    op.create_index(op.f('ix_email_history_id'), 'email_history', ['id'], unique=False)
    op.create_index(op.f('ix_email_history_kantei_record_id'), 'email_history', ['kantei_record_id'], unique=False)
    op.create_index(op.f('ix_email_history_message_id'), 'email_history', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_history_recipient_email'), 'email_history', ['recipient_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_history_recipient_email'), table_name='email_history')
    op.drop_index(op.f('ix_email_history_message_id'), table_name='email_history')
    op.drop_index(op.f('ix_email_history_kantei_record_id'), table_name='email_history')
    op.drop_index(op.f('ix_email_history_id'), table_name='email_history')
    op.drop_index('idx_email_status', table_name='email_history')
    op.drop_index('idx_email_recipient', table_name='email_history')
    op.drop_index('idx_email_message_id', table_name='email_history')
    op.drop_index('idx_email_kantei_sent', table_name='email_history')
    op.drop_table('email_history')
    op.drop_index(op.f('ix_template_settings_user_id'), table_name='template_settings')
    op.drop_index(op.f('ix_template_settings_id'), table_name='template_settings')
    op.drop_index('idx_template_user', table_name='template_settings')
    op.drop_index('idx_template_updated', table_name='template_settings')
    op.drop_table('template_settings')
    op.drop_index(op.f('ix_kantei_records_user_id'), table_name='kantei_records')
    op.drop_index(op.f('ix_kantei_records_id'), table_name='kantei_records')
    op.drop_index(op.f('ix_kantei_records_client_name'), table_name='kantei_records')
    op.drop_index('idx_kantei_user_created', table_name='kantei_records')
    op.drop_index('idx_kantei_status', table_name='kantei_records')
    op.drop_index('idx_kantei_created_at', table_name='kantei_records')
    op.drop_index('idx_kantei_client_name', table_name='kantei_records')
    op.drop_table('kantei_records')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_utage_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_utage_subscription', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index('idx_system_public', table_name='system_settings')
    op.drop_index('idx_system_key', table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
