"""add_font_size_design_pattern_to_template_settings

Revision ID: cc4f18169325
Revises: b23cbb44689a
Create Date: 2025-09-23 00:30:27.852123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc4f18169325'
down_revision: Union[str, Sequence[str], None] = 'b23cbb44689a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_settings', sa.Column('font_size', sa.String(length=20), nullable=True, comment='フォントサイズ: small/medium/large'))
    op.add_column('template_settings', sa.Column('design_pattern', sa.String(length=50), nullable=True, comment='デザインパターン: modern-minimal等'))
    op.alter_column('users', 'operator_name',
               existing_type=sa.VARCHAR(length=255),
               comment='鑑定士名',
               existing_comment='運営者名',
               existing_nullable=True)
    op.alter_column('users', 'utage_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='UTAGE ユーザーID',
               existing_comment='UTAGE連携ID',
               existing_nullable=True)
    op.alter_column('users', 'subscription_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='課金状態更新日時',
               existing_comment='課金状態最終更新時刻',
               existing_nullable=True)
    op.drop_index(op.f('idx_user_utage_subscription'), table_name='users')
    op.drop_index(op.f('ix_users_utage_user_id'), table_name='users')
    op.create_index('idx_user_subscription_status', 'users', ['subscription_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_subscription_status', table_name='users')
    op.create_index(op.f('ix_users_utage_user_id'), 'users', ['utage_user_id'], unique=True)
    op.create_index(op.f('idx_user_utage_subscription'), 'users', ['utage_user_id', 'subscription_status'], unique=False)
    op.alter_column('users', 'subscription_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='課金状態最終更新時刻',
               existing_comment='課金状態更新日時',
               existing_nullable=True)
    op.alter_column('users', 'utage_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='UTAGE連携ID',
               existing_comment='UTAGE ユーザーID',
               existing_nullable=True)
    op.alter_column('users', 'operator_name',
               existing_type=sa.VARCHAR(length=255),
               comment='運営者名',
               existing_comment='鑑定士名',
               existing_nullable=True)
    op.drop_column('template_settings', 'design_pattern')
    op.drop_column('template_settings', 'font_size')
    # ### end Alembic commands ###
